export const exampleWeatherData = {
  request: {
    type: "City",
    query: "Madrid, Spain",
    language: "en",
    unit: "m",
  },
  location: {
    name: "Madrid",
    country: "Spain",
    region: "Madrid",
    lat: "40.400",
    lon: "-3.683",
    timezone_id: "Europe/Madrid",
    localtime: "2022-06-29 20:05",
    localtime_epoch: 1656533100,
    utc_offset: "2.0",
  },
  current: {
    observation_time: "06:05 PM",
    temperature: 30,
    weather_code: 113,
    weather_icons: [
      "https://assets.weatherstack.com/images/wsymbols01_png_64/wsymbol_0001_sunny.png",
    ],
    weather_descriptions: ["Sunny"],
    wind_speed: 24,
    wind_degree: 240,
    wind_dir: "WSW",
    pressure: 1012,
    precip: 0,
    humidity: 17,
    cloudcover: 0,
    feelslike: 28,
    uv_index: 8,
    visibility: 10,
    is_day: "yes",
  },
};
